### ISSUE TITLE
The accuracy value is different from the in-game display.

### ISSUE THREAD

**Issue by rynan4818** [kOFReadie/BSDataPuller#6]
The in-game and HTTPStatus accuracy indications are correct, but the DataPuller is slightly larger.

https://youtu.be/4sb6Hgjc3HY

The maximum score when the total number of notes in the map is 44.
115+(115x2x4)+(115x4x8)+(115x8x(44-13))=33235

32027/33235=0.96365 →96.37%

**Comment by chenxiaolong** [comment]
My pull request (#5) should have the side effect of fixing this because I updated the code to get maximum score from the `ScoreController.immediateMaxPossibleScoreDidChangeEvent` event instead of the `scoreController.immediateMaxPossibleRawScore` field. I'm not sure why `immediateMaxPossibleRawScore` is slightly larger.

**Comment by kOFReadie** [comment]
> My pull request (#5) should have the side effect of fixing this because I updated the code to get maximum score from the `ScoreController.immediateMaxPossibleScoreDidChangeEvent` event instead of the `scoreController.immediateMaxPossibleRawScore` field. I'm not sure why `immediateMaxPossibleRawScore` is slightly larger.

Yes I've seen your changes and I've been aware of this issue but the value difference was so minor that I never bothered to fix it, I have implemented your changes but I won't be releasing an update till I've tweaked a few other things.

**Comment by chenxiaolong** [comment]
Thank you!
