### ISSUE TITLE
Potential Counter+ conflict / soft lock

### ISSUE THREAD

**Issue by cadavren** [kOFReadie/BSDataPuller#8]
Hello !
I've recently got an issue with Counter+ menu soft locking my game when in FPFC mod. I asked Caeden first and it might be because of conflicts with one or more mods, including DataPuller !

Here is the link for the specific lines of the logs and comments Caeden made :
https://github.com/Caeden117/CountersPlus/issues/78#issuecomment-758207890

here are the logs if you need to see more :

Counter+ log : 
[_latest.log](https://github.com/kOFReadie/BSDataPuller/files/5849542/_latest.log)

Beatsaber log :
[_latest.log](https://github.com/kOFReadie/BSDataPuller/files/5849536/_latest.log)

Data puller log
[_latest.log](https://github.com/kOFReadie/BSDataPuller/files/5849534/_latest.log)

If anything I might be able to give more details or specific infos if asked !

**Comment by kOFReadie** [comment]
Hi I am aware of this an I noticed it when I was updating the mod for my next release. It was due to my mod not handling the tutorial level properly. I have fixed this issue and I am just tweaking a few other bits before the next release that should be out soon. Im going to close this issue as its been fixed in a recent commit.
